version: '3.8'

services:
  ai-video-generator:
    build:
      context: .
      args:
        - BUILDKIT_INLINE_CACHE=0
    container_name: ai-video-generator
    ports:
      - "7860:7860"
    volumes:
      - ./outputs:/app/outputs
      - ./hf_download:/app/hf_download
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
